.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SCHLEUDER\-CLI" "8" "January 2017" "" ""
.
.SH "NAME"
schleuder\-cli \- manage \fBschleuder\fR(8)\-lists, subscriptions, and keys\.
.
.SH "SYNOPSIS"
\fBschleuder\-cli\fR \fIcmd\fR <args\.\.\.>
.
.P
\fBschleuder\-cli\fR help
.
.SH "DESCRIPTION"
schleuder\-cli is a command line tool to create, configure, and delete schleuder\-lists, subscriptions, and OpenPGP\-keys\.
.
.P
It uses the \fBschleuder\fR(8) API, provided by \fBschleuder\-api\-daemon\fR(8)\.
.
.P
Authentication and TLS\-verification are mandatory\. You need an API\-key and the fingerprint of the TLS\-certificate of \fBschleuer\-api\-daemon\fR(8), respectively\. Both should be provided by the operators of \fBschleuer\-api\-daemon\fR(8)\.
.
.P
schleuder\-cli does \fInot\fR authorize access\. Only people who are supposed to have full access to all lists should be allowed to use it on/with your server\.
.
.SH "ENVIRONMENT"
.
.SS "Configuration"
SchleuderCli reads its settings from a file that it by default expects at \fB$HOME/\.schleuder\-cli/schleuder\-cli\.yml\fR\. To make it read a different file set the environment variable \fBSCHLEUDER_CLI_CONFIG\fR to the path to your file\. E\.g\.:
.
.IP "" 4
.
.nf

SCHLEUDER_CLI_CONFIG=/usr/local/etc/schleuder\-cli\.yml schleuder\-cli \.\.\.
.
.fi
.
.IP "" 0
.
.P
The configuration file specifies how to connect to the Schleuder API\. If it doesn\'t exist, it will be filled with the default settings\.
.
.P
The default settings will work out of the box with the default settings of Schleuder if both are running on the same host\.
.
.SS "Options"
These are the configuration file options and their default values:
.
.TP
\fBhost\fR
The hostname (or IP\-address) to connect to\. Default: \fIlocalhost\fR\.
.
.TP
\fBpost\fR
The port to connect to\. Default: \fI4443\fR\.
.
.TP
\fBtls_fingerprint\fR
TLS\-fingerprint of the Schleuder API\. To be fetched from the API operators\. Default: empty\.
.
.TP
\fBapi_key\fR
Key to authenticate with against the Schleuder API\. To be fetched from the API operators\. Default: empty\.
.
.SH "FILES"
.
.TP
\fB$HOME/\.schleuder\-cli/schleuder\-cli\.yml\fR
default path of schleuder\-cli configuration file\.
.
.P
The configuration file is formatted as YAML\. See \fIhttp://www\.yaml\.org/\fR for more details\.
.
.SH "BUGS"
Known bugs are listed on the schleuder\-cli bugtracker at \fIhttps://0xacab\.org/schleuder/schleuder\-cli/issues\fR
.
.SH "SEE ALSO"
\fBschleuder\fR(8), \fBschleuder\-api\-daemon\fR(8)\.
.
.TP
Website of \fBschleuder\-cli\fR
\fIhttps://0xacab\.org/schleuder/schleuder\-cli/\fR
.
.TP
Website of \fBschleuder\fR
\fIhttps://schleuder\.nadir\.org/\fR
.
.TP
More extensive documentation for \fBschleuder\fR
\fIhttps://schleuder\.nadir\.org/docs/\fR
.
.TP
\fBschleuder\-web\fR, the web interface for list\-management
\fIhttps://0xacab\.org/schleuder/schleuder\-web/\fR

