---
default:
  image: $IMAGE_REGISTRY:debian-generic

variables:
  IMAGE_REGISTRY: $CI_REGISTRY/schleuder/schleuder-ci-images

stages:
  - static
  - test

workflow:
  rules:
    # Don't create pipelines for branches, if associated MR do exist, or tags.
    # Otherwise, create pipelines.
    # This prevents duplicated pipelines and wasted resources.
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS || $CI_COMMIT_TAG
      when: never
    - when: always

.test_ruby: &test_ruby
  script:
    - eatmydata gem install bundler $bundler_args
    - eatmydata bundle install --jobs $(nproc) --path vendor
      # The integration tests require a running schleuder-api-daemon, which we don't have in this setup (yet?)
    - eatmydata bundle exec rspec spec/schleuder-cli

codespell:
  rules:
    - if: $CI_MERGE_REQUEST_IID
  script:
    # Run codespell to check for spelling errors, using a config to skip code of installed 
    # dependencies, to ignore warnings about binary files and to check file names as well.
    - codespell -S vendor -q 2 -f
  stage: static

ruby:2.6:
  image: $IMAGE_REGISTRY:schleuder-ruby2.6
  variables:
    bundler_args: "-v 2.4.22"
  <<: *test_ruby
ruby:2.7:
  image: $IMAGE_REGISTRY:schleuder-ruby2.7
  variables:
    bundler_args: "-v 2.4.22"
  <<: *test_ruby
ruby:3.0:
  image: $IMAGE_REGISTRY:schleuder-ruby3.0
  <<: *test_ruby
ruby:3.1:
  image: $IMAGE_REGISTRY:schleuder-ruby3.1
  <<: *test_ruby
ruby:3.2:
  image: $IMAGE_REGISTRY:schleuder-ruby3.2
  <<: *test_ruby
ruby:3.3:
  image: $IMAGE_REGISTRY:schleuder-ruby3.3
  <<: *test_ruby

bundler:audit:
  image: ruby:2.7
  only:
    - schedules
  script:
    - gem install bundler-audit --no-document
    - bundle install --jobs $(nproc) --path vendor
    - bundle-audit update
    - bundle-audit check
